import React from "react";
import {
  CreditCard,
  Briefcase,
  Key,
  ShieldCheck,
  Building,
  ShoppingCart,
  Truck,
  FileCheck,
  Users,
  LucideIcon,
} from "lucide-react";

export type ModelClassId =
  | "credit_loan"
  | "employment"
  | "lease"
  | "license_ip"
  | "merger_acquisition"
  | "purchase_sale"
  | "service_supply"
  | "settlement_release"
  | "shareholder_rights";

export interface ClassMetadata {
  id: ModelClassId;
  label: string;
  shortLabel: string;
  blurb: string;
  tag: string;
  icon: LucideIcon;
  bg: string;
  fg: string;
  sampleDoc: string;
  mockClause: string;
  mockRisk: string;
  docCol: string;
  docRow: string;
  specCol: string;
  specRow: string;
  probabilities: Record<ModelClassId, number>;
}

export const MODEL_CLASSES: ModelClassId[] = [
  "credit_loan",
  "employment",
  "lease",
  "license_ip",
  "merger_acquisition",
  "purchase_sale",
  "service_supply",
  "settlement_release",
  "shareholder_rights",
];

export const CLASS_METADATA: Record<ModelClassId, ClassMetadata> = {
  credit_loan: {
    id: "credit_loan",
    label: "Credit & Loan",
    shortLabel: "Credit &\nLoan",
    blurb: "Loan agreements, credit facilities, mortgages",
    tag: "Credit Loan",
    icon: CreditCard,
    bg: "#FEF9C3",
    fg: "#854D0E",
    sampleDoc: "Credit_Loan_Agreement.pdf",
    mockClause: "Section 4.1 — Default Interest Rate (18% p.a.)",
    mockRisk: "High floating interest margin clause detected",
    docCol: "1 / 5",
    docRow: "1 / 2",
    specCol: "1 / 5",
    specRow: "1 / 2",
    probabilities: {
      credit_loan: 0.945,
      purchase_sale: 0.023,
      service_supply: 0.012,
      employment: 0.005,
      lease: 0.004,
      license_ip: 0.003,
      merger_acquisition: 0.003,
      settlement_release: 0.003,
      shareholder_rights: 0.002,
    },
  },
  employment: {
    id: "employment",
    label: "Employment",
    shortLabel: "Employment\nAgreement",
    blurb: "Employment contracts, non-compete, workplace rights",
    tag: "Employment",
    icon: Briefcase,
    bg: "#DBEAFE",
    fg: "#1E40AF",
    sampleDoc: "Employment_Contract.pdf",
    mockClause: "Clause 7.3 — Non-Compete Period (24 months)",
    mockRisk: "Clause 7.3 — Non-compete restriction unusually broad",
    docCol: "5 / 9",
    docRow: "1 / 2",
    specCol: "5 / 9",
    specRow: "1 / 2",
    probabilities: {
      employment: 0.968,
      service_supply: 0.015,
      settlement_release: 0.006,
      license_ip: 0.004,
      credit_loan: 0.002,
      lease: 0.002,
      merger_acquisition: 0.001,
      purchase_sale: 0.001,
      shareholder_rights: 0.001,
    },
  },
  lease: {
    id: "lease",
    label: "Lease",
    shortLabel: "Lease\nAgreement",
    blurb: "Commercial & residential leases, tenancy agreements",
    tag: "Lease",
    icon: Key,
    bg: "#FFEDD5",
    fg: "#9A3412",
    sampleDoc: "Commercial_Lease_Deed.pdf",
    mockClause: "Clause 12.2 — Early Termination Penalty",
    mockRisk: "Unilateral rent escalation clause without notice",
    docCol: "9 / 13",
    docRow: "1 / 2",
    specCol: "9 / 13",
    specRow: "1 / 2",
    probabilities: {
      lease: 0.952,
      purchase_sale: 0.021,
      credit_loan: 0.011,
      service_supply: 0.006,
      employment: 0.003,
      license_ip: 0.003,
      settlement_release: 0.002,
      merger_acquisition: 0.001,
      shareholder_rights: 0.001,
    },
  },
  license_ip: {
    id: "license_ip",
    label: "License & IP",
    shortLabel: "License &\nIP",
    blurb: "IP licensing, technology transfer, patent grants",
    tag: "License IP",
    icon: ShieldCheck,
    bg: "#FEF3C7",
    fg: "#92400E",
    sampleDoc: "IP_License_Agreement.pdf",
    mockClause: "Section 3.4 — Royalty Audit & Territorial Rights",
    mockRisk: "Exclusivity clause limits sub-licensing in APAC",
    docCol: "1 / 5",
    docRow: "2 / 3",
    specCol: "1 / 5",
    specRow: "2 / 3",
    probabilities: {
      license_ip: 0.938,
      service_supply: 0.028,
      shareholder_rights: 0.012,
      employment: 0.008,
      merger_acquisition: 0.005,
      purchase_sale: 0.004,
      settlement_release: 0.002,
      credit_loan: 0.002,
      lease: 0.001,
    },
  },
  merger_acquisition: {
    id: "merger_acquisition",
    label: "Merger & Acquisition",
    shortLabel: "Merger &\nAcquisition",
    blurb: "M&A agreements, share purchase, corporate restructuring",
    tag: "Merger Acquisition",
    icon: Building,
    bg: "#D1FAE5",
    fg: "#065F46",
    sampleDoc: "Merger_Acquisition_TermSheet.pdf",
    mockClause: "Clause 9.1 — Indemnification Escrow (15%)",
    mockRisk: "Material Adverse Effect (MAE) definition too narrow",
    docCol: "5 / 9",
    docRow: "2 / 3",
    specCol: "5 / 9",
    specRow: "2 / 3",
    probabilities: {
      merger_acquisition: 0.961,
      shareholder_rights: 0.018,
      purchase_sale: 0.010,
      license_ip: 0.004,
      credit_loan: 0.003,
      settlement_release: 0.002,
      service_supply: 0.001,
      employment: 0.0005,
      lease: 0.0005,
    },
  },
  purchase_sale: {
    id: "purchase_sale",
    label: "Purchase & Sale",
    shortLabel: "Purchase &\nSale",
    blurb: "Asset sale, goods purchase, equipment supply",
    tag: "Purchase Sale",
    icon: ShoppingCart,
    bg: "#E0E7FF",
    fg: "#3730A3",
    sampleDoc: "Asset_Purchase_Agreement.pdf",
    mockClause: "Article 5 — Warranty & Liability Limits",
    mockRisk: "Capped aggregate liability below contract value",
    docCol: "9 / 13",
    docRow: "2 / 3",
    specCol: "9 / 13",
    specRow: "2 / 3",
    probabilities: {
      purchase_sale: 0.941,
      service_supply: 0.026,
      lease: 0.014,
      credit_loan: 0.008,
      merger_acquisition: 0.005,
      license_ip: 0.003,
      settlement_release: 0.001,
      employment: 0.001,
      shareholder_rights: 0.001,
    },
  },
  service_supply: {
    id: "service_supply",
    label: "Service & Supply",
    shortLabel: "Service &\nSupply",
    blurb: "Master service agreements, vendor contracts, SLA",
    tag: "Service Supply",
    icon: Truck,
    bg: "#CFFAFE",
    fg: "#155E75",
    sampleDoc: "Master_Service_Agreement.pdf",
    mockClause: "SLA Schedule B — Uptime Guarantee & Credits",
    mockRisk: "Termination for convenience period too short (7 days)",
    docCol: "1 / 5",
    docRow: "3 / 4",
    specCol: "1 / 5",
    specRow: "3 / 4",
    probabilities: {
      service_supply: 0.957,
      purchase_sale: 0.020,
      license_ip: 0.011,
      employment: 0.005,
      settlement_release: 0.003,
      credit_loan: 0.002,
      lease: 0.001,
      merger_acquisition: 0.0005,
      shareholder_rights: 0.0005,
    },
  },
  settlement_release: {
    id: "settlement_release",
    label: "Settlement & Release",
    shortLabel: "Settlement &\nRelease",
    blurb: "Dispute settlements, mutual releases, compromise deeds",
    tag: "Settlement Release",
    icon: FileCheck,
    bg: "#F3E8FF",
    fg: "#6B21A8",
    sampleDoc: "Settlement_Release_Deed.pdf",
    mockClause: "Clause 2.3 — General Mutual Release of Claims",
    mockRisk: "Scope of unknown claims waiver needs narrowing",
    docCol: "5 / 9",
    docRow: "3 / 4",
    specCol: "5 / 9",
    specRow: "3 / 4",
    probabilities: {
      settlement_release: 0.949,
      employment: 0.022,
      service_supply: 0.013,
      credit_loan: 0.007,
      shareholder_rights: 0.004,
      purchase_sale: 0.002,
      license_ip: 0.0015,
      merger_acquisition: 0.001,
      lease: 0.0005,
    },
  },
  shareholder_rights: {
    id: "shareholder_rights",
    label: "Shareholder Rights",
    shortLabel: "Shareholder\nRights",
    blurb: "Shareholders agreements, voting rights, drag/tag along",
    tag: "Shareholder Rights",
    icon: Users,
    bg: "#FCE7F3",
    fg: "#9D174D",
    sampleDoc: "Shareholders_Agreement.pdf",
    mockClause: "Clause 14 — Tag-Along & Drag-Along Thresholds",
    mockRisk: "Supermajority voting requirement blocks routine decisions",
    docCol: "9 / 13",
    docRow: "3 / 4",
    specCol: "9 / 13",
    specRow: "3 / 4",
    probabilities: {
      shareholder_rights: 0.963,
      merger_acquisition: 0.019,
      credit_loan: 0.008,
      license_ip: 0.004,
      settlement_release: 0.003,
      purchase_sale: 0.0015,
      service_supply: 0.0008,
      employment: 0.0004,
      lease: 0.0003,
    },
  },
};

export function getClassMetadata(classId: ModelClassId): ClassMetadata {
  return CLASS_METADATA[classId] || CLASS_METADATA.employment;
}
